# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    name: Build frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      REMOTE_SFTP_LOGIN: ${{ secrets.REMOTE_SFTP_LOGIN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Building react app
        run: |
          npm i 
          npm run build --if-present
      - name: Install packages
        run: |
          sudo apt install -y lftp
      - name: Upload artifact to server
        run: |
          lftp -d -e "set sftp:auto-confirm yes; open $REMOTE_SFTP_LOGIN; mirror -X ./dist/* -X .*/ --reverse; bye"
